spring.datasource.url=jdbc:mysql://localhost:3306/recipe_db
spring.datasource.username=your_username
spring.datasource.password=your_password
spoonacular.api.key=your_api_key

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
